# To avoid using the new text lockfile which is not compatible with cloudflare yet
# https://github.com/#oven-sh/bun/discussions/16846#discussioncomment-11989536
# saveTextLockfile = false
# The workaround is creating an empty bun.lockdb and make sure BUN_VERSION is > 1.2.1

[install.cache]
# the directory to use for the cache
# dir = ".bun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
# disable = false

# when true, always resolve the latest versions from the registry
# disableManifest = false