siteName: poko
productionUrl: https://poko.m4rr.co
logo: /_images/poko-logo-rvb-02.webp
languages:
  - code: en
    name: English
    customUrlPrefix:
      prefix: /
    status: published
    isCmsDefault: true
    isWebsiteDefault: true
