siteName: mookaï asbl
productionUrl: https://www.mookai.be
logo: /_images/mookai-logo-RVB-SANS-BORDS-38.webp
cssHead: |-
  @font-face {
    font-family: "Chantal";
    src: url("/assets/files/chantal-medium-regular.ttf") format("truetype");
    font-weight: 500;
    font-style: normal;
  }
languages:
  - code: fr
    status: published
    keepUrlPrefix: false
    name: Français
    customUrlPrefix:
      prefix: ''
    isCmsDefault: false
    isWebsiteDefault: false
collections:
  - services
  - projects
  - people
  - organizations
  - creativeWorks
  - articles
newTabLinkTypes:
  - external
